language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
env:
  matrix:
   - DJANGO=1.8.13
   - DJANGO=1.9.7

install:
  - pip install -q Django==$DJANGO

script:
  - python manage.py test
