language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
env:
  matrix:
   - DJANGO="Django<1.8"
   - DJANGO="Django<1.9"
   - DJANGO="Django<1.10"

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors

script:
  - python manage.py test
